In [2]:
%pip install langdetect
%pip install deep-translator

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: langdetect in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (1.0.9)
Requirement already satisfied: six in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from langdetect) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from deep-translator) (4.13.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\documents\team 3\simbaai_t3\simba_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.1.31)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from langdetect import detect
from deep_translator import GoogleTranslator

In [4]:
df = pd.read_csv('transport_data.csv')

df.head()

,title,summary,content,links,url
0,Transport,Transport (in British English) or transportati...,Air\nArmored fighting vehicle\nBicycle\nBus\nC...,"['/wiki/File:High_Five.jpg', '/wiki/Transfer_(...",https://en.wikipedia.org/wiki/Transport
1,Rail transport,\nRail transport (also known as train transpor...,\nRail transport (also known as train transpor...,"['/wiki/Transfer_(public_transit)', '/wiki/Bat...",https://en.wikipedia.org/wiki/Rail_transport
2,Public transport,\nPublic transport (also known as public trans...,\nAir\nArmored fighting vehicle\nBicycle\nBus\...,"['/wiki/Transfer_(public_transit)', '/wiki/Pro...",https://en.wikipedia.org/wiki/Public_transport
3,List of ministries of transport by country,\nA ministry of transport or transportation is...,\nA ministry of transport or transportation is...,['/wiki/Sini%C5%A1a_Hajda%C5%A1_Don%C4%8Di%C4%...,https://en.wikipedia.org/wiki/List_of_ministri...
4,Land transport,\nLand transport is the transport or movement ...,\nLand transport is the transport or movement ...,"['/wiki/Portal:Environment', '/wiki/Transport_...",https://en.wikipedia.org/wiki/Land_transport

In [34]:
# to check for missing values in each row on the columns
missing_values = df.isnull()
for column in missing_values.columns.values.tolist():
    print (missing_values[column].value_counts())
    print("")

title
False    8659
Name: count, dtype: int64

summary
False    6610
True     2049
Name: count, dtype: int64

content
False    6622
True     2037
Name: count, dtype: int64

links
False    8659
Name: count, dtype: int64

url
False    8659
Name: count, dtype: int64

In [35]:
# percentage of the missing values as per columns
summary_percentage = missing_values['summary'].value_counts() / df['summary'].size 
content_percentage = missing_values['content'].value_counts() / df['summary'].size 

print(content_percentage)
print(summary_percentage)

# 23% of our data is empty

content
False    0.764753
True     0.235247
Name: count, dtype: float64
summary
False    0.763368
True     0.236632
Name: count, dtype: float64

In [30]:
#display the duplicate rows
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 5)

In [31]:
#removing the duplicates
df = df.drop_duplicates()

In [32]:
# check if the duplicates are gone
print("number of duplicate rows: ", df.duplicated())

number of duplicate rows:  0       False
1       False
2       False
3       False
4       False
        ...
9992    False
9993    False
9994    False
9995    False
9996    False
Length: 8659, dtype: bool

In [36]:
# Drop rows where both columns 'content' and 'summary' are empty
df1=df
df_cleaned = df1.dropna(subset=['content', 'summary'], how='all')

In [39]:
missing_valuesdf1 = df_cleaned.isnull()
for column in missing_valuesdf1.columns.values.tolist():
    print (missing_valuesdf1[column].value_counts())
    print("")

title
False    6622
Name: count, dtype: int64

summary
False    6610
True       12
Name: count, dtype: int64

content
False    6622
Name: count, dtype: int64

links
False    6622
Name: count, dtype: int64

url
False    6622
Name: count, dtype: int64

In [40]:
# after removing the duplicates 
# we see most of the raws missed data both in content and summary sections
# this being only 12 rows we can replace them with Not Available

# Function to extract first 25 words
def get_summary(text):
    words = text.split()
    return ' '.join(words[:25]) if len(words) > 25 else text

# Update only rows where 'summary' is NaN
df_cleaned.loc[df['summary'].isna(), 'summary'] = df_cleaned['content'].apply(get_summary)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\3408418457.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.loc[df['summary'].isna(), 'summary'] = df_cleaned['content'].apply(get_summary)

In [41]:
missing_valuesdf1 = df_cleaned.isnull()
for column in missing_valuesdf1.columns.values.tolist():
    print (missing_valuesdf1[column].value_counts())
    print("")
    
    
    
    #it worked no more empty values

title
False    6622
Name: count, dtype: int64

summary
False    6622
Name: count, dtype: int64

content
False    6622
Name: count, dtype: int64

links
False    6622
Name: count, dtype: int64

url
False    6622
Name: count, dtype: int64

In [43]:
# as seen from the dataset above, we have to remove the \n from the summary and content column
# there are many \n in the content and the summary column
#this removes all the \n from the content table and summart
df_cleaned["content"] = df_cleaned["content"].str.replace("\n", " ", regex=True)
df_cleaned["summary"] = df_cleaned["summary"].str.replace("\n", " ", regex=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\1772156908.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["content"] = df_cleaned["content"].str.replace("\n", " ", regex=True)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\1772156908.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["summary"] = df_cleaned["summary"].str.replace("\n", " ", regex=True)

In [48]:
df_cleaned.head()

,title,summary,content,links,url
0,Transport,Transport (in British English) or transportati...,Air Armored fighting vehicle Bicycle Bus Cable...,"['/wiki/File:High_Five.jpg', '/wiki/Transfer_(...",https://en.wikipedia.org/wiki/Transport
1,Rail transport,Rail transport (also known as train transport...,Rail transport (also known as train transport...,"['/wiki/Transfer_(public_transit)', '/wiki/Bat...",https://en.wikipedia.org/wiki/Rail_transport
2,Public transport,Public transport (also known as public transp...,Air Armored fighting vehicle Bicycle Bus Cabl...,"['/wiki/Transfer_(public_transit)', '/wiki/Pro...",https://en.wikipedia.org/wiki/Public_transport
3,List of ministries of transport by country,A ministry of transport or transportation is ...,A ministry of transport or transportation is ...,['/wiki/Sini%C5%A1a_Hajda%C5%A1_Don%C4%8Di%C4%...,https://en.wikipedia.org/wiki/List_of_ministri...
4,Land transport,Land transport is the transport or movement o...,Land transport is the transport or movement o...,"['/wiki/Portal:Environment', '/wiki/Transport_...",https://en.wikipedia.org/wiki/Land_transport

In [49]:
%pip install wordninja

Collecting wordninja
  Downloading wordninja-2.0.0.tar.gz (541 kB)
     ---------------------------------------- 0.0/541.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/541.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/541.6 kB ? eta -:--:--
     ------------------- -------------------- 262.1/541.6 kB ? eta -:--:--
     ------------------- -------------------- 262.1/541.6 kB ? eta -:--:--
     ------------------- -------------------- 262.1/541.6 kB ? eta -:--:--
     ------------------------------------ 541.6/541.6 kB 423.4 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: wordninja
  Building wheel for wordninja (pyproject.toml): started
  Building wheel for wordninja (pyproject.toml): finished with status 'done'
  Created wheel for wordninja: filename=wordninja-2.0.0-py3-none-any.whl size=541558 sha256=ecf99140d567f18763eb006c67e41d57d9bc9fac2b06c82f771e54da1bcd0f7d
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\8c\28\16\1ee6c4de039d112b6d448c7aa61f0f62c27cfcd0d2b08762fb
Successfully built wordninja
Installing collected packages: wordninja
Successfully installed wordninja-2.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import wordninja

# Apply word splitting
df_cleaned['summary'] =df_cleaned['summary'].apply(lambda x: " ".join(wordninja.split(x)))
df_cleaned['content'] =df_cleaned['content'].apply(lambda x: " ".join(wordninja.split(x)))

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\1452805111.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['summary'] =df_cleaned['summary'].apply(lambda x: " ".join(wordninja.split(x)))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\1452805111.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['content'] =df_cleaned['content'].apply(lambda x: " ".join(wordninja.split(x)))

In [51]:
from langdetect import detect
from deep_translator import GoogleTranslator


# Function to detect language
def detect_language(text):
    try:
        return detect(text)
    except:
        return "unknown"  # Handle errors

# Detect language
df_cleaned['Language'] = df['content'].apply(detect_language)

# Filter only non-English rows
non_english_df = df_cleaned[df_cleaned['Language'] != 'en'].copy()  # Copy to avoid warnings

# Function to translate text
def translate_text(text):
    return GoogleTranslator(source='auto', target='en').translate(text)

# Apply translation **only to non-English rows**
non_english_df['EnglishText'] = non_english_df['Language'].apply(translate_text)

# Merge back translated texts into original DataFrame
df.update(non_english_df)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5404\4098121803.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Language'] = df['content'].apply(detect_language)

In [67]:
df_cleaned['links'] = df['links']

df_cleaned.head()

,title,summary,content,links,url
0,Transport,Transport in British English or transportation...,Air Armored fighting vehicle Bicycle Bus Cable...,"['/wiki/File:High_Five.jpg', '/wiki/Transfer_(...",https://en.wikipedia.org/wiki/Transport
1,Rail transport,Rail transport also known as train transport i...,Rail transport also known as train transport i...,"['/wiki/Transfer_(public_transit)', '/wiki/Bat...",https://en.wikipedia.org/wiki/Rail_transport
2,Public transport,Public transport also known as public transpor...,Air Armored fighting vehicle Bicycle Bus Cable...,"['/wiki/Transfer_(public_transit)', '/wiki/Pro...",https://en.wikipedia.org/wiki/Public_transport
3,List of ministries of transport by country,A ministry of transport or transportation is a...,A ministry of transport or transportation is a...,['/wiki/Sini%C5%A1a_Hajda%C5%A1_Don%C4%8Di%C4%...,https://en.wikipedia.org/wiki/List_of_ministri...
4,Land transport,Land transport is the transport or movement of...,Land transport is the transport or movement of...,"['/wiki/Portal:Environment', '/wiki/Transport_...",https://en.wikipedia.org/wiki/Land_transport

In [79]:
# removing links from the summary and content columns
#remove urls
import re

def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

#This function removes punctuations
def remove_punct(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df_cleaned['content'] = df_cleaned['content'].apply(lambda x: remove_url(x))
df_cleaned['summary'] = df_cleaned['summary'].apply(lambda x: remove_url(x))
df_cleaned['title'] = df_cleaned['title'].apply(lambda x: remove_url(x))

In [72]:
df_cleaned = df_cleaned.drop(columns=['links'])

In [84]:
df_cleaned.tail(20)

,title,summary,content,url
9973,Japan Civil Aviation Bureau,The Japan Civil Aviation Bureau K k kyo ku J C...,The Japan Civil Aviation Bureau K k kyo ku J C...,https://en.wikipedia.org/wiki/Japan_Civil_Avia...
9974,USS General A. W. Brewster,USS General A W Brewster AP 155 was a General ...,Kaiser Co Inc Richmond California after 10 Apr...,https://en.wikipedia.org/wiki/USS_General_A._W...
9975,Speed bump,Speed bumps also called traffic thresholds spe...,Speed bumps also called traffic thresholds spe...,https://en.wikipedia.org/wiki/Speed_bump
9977,Trams in Rijeka,Tram traffic in Rijeka Fiume was introduced in...,Tram traffic in Rijeka Fiume was introduced in...,https://en.wikipedia.org/wiki/Trams_in_Rijeka
9978,R184 road (Ireland),The R 184 road is a regional road in Ireland l...,County Monaghan leaves the R 162 near Ball y b...,https://en.wikipedia.org/wiki/R184_road_(Ireland)
9979,Government ministries of Samoa,Samoa has 15 government ministries each of whi...,O le Ao o le Malo head of state Tui male ali i...,https://en.wikipedia.org/wiki/Government_minis...
9980,T-kort,T kort stylized as t kort is a digital ticketi...,T kort stylized as t kort is a digital ticketi...,https://en.wikipedia.org/wiki/T-kort
9981,Phil Twyford,Philip Stoner Twyford born 4 May 1963 is a pol...,Philip Stoner Twyford born 4 May 1963 is a pol...,https://en.wikipedia.org/wiki/Phil_Twyford
9982,Japanese submarine Yu 1002,Yu 1002 was an Imperial Japanese Army transpor...,Surrendered August 1945 Scuttled or scrapped 2...,https://en.wikipedia.org/wiki/Japanese_submari...
9983,Airlink Cargo,Air link Cargo is a division of S A Air link P...,Air link Cargo is a division of S A Air link P...,https://en.wikipedia.org/wiki/Airlink_Cargo
9984,Government Transformation Programme (Malaysia),The Government Transformation Programme GT P i...,Early life Electoral history Controversies Pri...,https://en.wikipedia.org/wiki/Government_Trans...
9985,Minitram,Mini tram was an automated guide way transit s...,Mini tram was an automated guide way transit s...,https://en.wikipedia.org/wiki/Minitram
9986,Pizza box,The pizza box or pizza package is a folding pa...,History of pizza Pizza delivery List of pizza ...,https://en.wikipedia.org/wiki/Pizza_box
9989,Japanese submarine Yu 1003,Yu 1003 was an Imperial Japanese Army transpor...,Surrendered August 1945 Scuttled or scrapped 2...,https://en.wikipedia.org/wiki/Japanese_submari...
9990,Jon Georg Dale,Jon Georg Dale born 16 June 1984 is a Norwegia...,Jon Georg Dale born 16 June 1984 is a Norwegia...,https://en.wikipedia.org/wiki/Jon_Georg_Dale
9992,Sukhoi Su-80,The Sukhoi Su 80 formerly known as the Sukhoi ...,The Sukhoi Su 80 formerly known as the Sukhoi ...,https://en.wikipedia.org/wiki/Sukhoi_Su-80
9993,Ocean gyre,In oceanography a gy re d a r is any large sys...,In oceanography a gy re d a r is any large sys...,https://en.wikipedia.org/wiki/Ocean_gyre
9994,Scottish Rail Holdings,Scottish Rail Holdings is an executive non dep...,Iain Do chert y Chair 1 Hannah Ross CEO 2 Cale...,https://en.wikipedia.org/wiki/Scottish_Rail_Ho...
9995,Ust-Danube Commercial Seaport,The Ust Danube Seaport is a state owned enterp...,The Ust Danube Seaport is a state owned enterp...,https://en.wikipedia.org/wiki/Ust-Danube_Comme...
9996,List of equipment of the United States Army du...,The following is a list of equipment of the Un...,The following is a list of equipment of the Un...,https://en.wikipedia.org/wiki/List_of_equipmen...

In [86]:
#resetting the index
df_cleaned = df_cleaned.reset_index(drop=True)  # drop=True removes old index

In [87]:
df_cleaned.tail(20)

,title,summary,content,url
6602,Japan Civil Aviation Bureau,The Japan Civil Aviation Bureau K k kyo ku J C...,The Japan Civil Aviation Bureau K k kyo ku J C...,https://en.wikipedia.org/wiki/Japan_Civil_Avia...
6603,USS General A. W. Brewster,USS General A W Brewster AP 155 was a General ...,Kaiser Co Inc Richmond California after 10 Apr...,https://en.wikipedia.org/wiki/USS_General_A._W...
6604,Speed bump,Speed bumps also called traffic thresholds spe...,Speed bumps also called traffic thresholds spe...,https://en.wikipedia.org/wiki/Speed_bump
6605,Trams in Rijeka,Tram traffic in Rijeka Fiume was introduced in...,Tram traffic in Rijeka Fiume was introduced in...,https://en.wikipedia.org/wiki/Trams_in_Rijeka
6606,R184 road (Ireland),The R 184 road is a regional road in Ireland l...,County Monaghan leaves the R 162 near Ball y b...,https://en.wikipedia.org/wiki/R184_road_(Ireland)
6607,Government ministries of Samoa,Samoa has 15 government ministries each of whi...,O le Ao o le Malo head of state Tui male ali i...,https://en.wikipedia.org/wiki/Government_minis...
6608,T-kort,T kort stylized as t kort is a digital ticketi...,T kort stylized as t kort is a digital ticketi...,https://en.wikipedia.org/wiki/T-kort
6609,Phil Twyford,Philip Stoner Twyford born 4 May 1963 is a pol...,Philip Stoner Twyford born 4 May 1963 is a pol...,https://en.wikipedia.org/wiki/Phil_Twyford
6610,Japanese submarine Yu 1002,Yu 1002 was an Imperial Japanese Army transpor...,Surrendered August 1945 Scuttled or scrapped 2...,https://en.wikipedia.org/wiki/Japanese_submari...
6611,Airlink Cargo,Air link Cargo is a division of S A Air link P...,Air link Cargo is a division of S A Air link P...,https://en.wikipedia.org/wiki/Airlink_Cargo
6612,Government Transformation Programme (Malaysia),The Government Transformation Programme GT P i...,Early life Electoral history Controversies Pri...,https://en.wikipedia.org/wiki/Government_Trans...
6613,Minitram,Mini tram was an automated guide way transit s...,Mini tram was an automated guide way transit s...,https://en.wikipedia.org/wiki/Minitram
6614,Pizza box,The pizza box or pizza package is a folding pa...,History of pizza Pizza delivery List of pizza ...,https://en.wikipedia.org/wiki/Pizza_box
6615,Japanese submarine Yu 1003,Yu 1003 was an Imperial Japanese Army transpor...,Surrendered August 1945 Scuttled or scrapped 2...,https://en.wikipedia.org/wiki/Japanese_submari...
6616,Jon Georg Dale,Jon Georg Dale born 16 June 1984 is a Norwegia...,Jon Georg Dale born 16 June 1984 is a Norwegia...,https://en.wikipedia.org/wiki/Jon_Georg_Dale
6617,Sukhoi Su-80,The Sukhoi Su 80 formerly known as the Sukhoi ...,The Sukhoi Su 80 formerly known as the Sukhoi ...,https://en.wikipedia.org/wiki/Sukhoi_Su-80
6618,Ocean gyre,In oceanography a gy re d a r is any large sys...,In oceanography a gy re d a r is any large sys...,https://en.wikipedia.org/wiki/Ocean_gyre
6619,Scottish Rail Holdings,Scottish Rail Holdings is an executive non dep...,Iain Do chert y Chair 1 Hannah Ross CEO 2 Cale...,https://en.wikipedia.org/wiki/Scottish_Rail_Ho...
6620,Ust-Danube Commercial Seaport,The Ust Danube Seaport is a state owned enterp...,The Ust Danube Seaport is a state owned enterp...,https://en.wikipedia.org/wiki/Ust-Danube_Comme...
6621,List of equipment of the United States Army du...,The following is a list of equipment of the Un...,The following is a list of equipment of the Un...,https://en.wikipedia.org/wiki/List_of_equipmen...